name       : dialog
version    : 0.9
release    : 1
source     :
    - http://invisible-island.net/datafiles/release/dialog.tar.gz : 81baec14cb7d76951763576ec276210b3a869e768ad5e2e6ee1cc53420ece8c9
license    : GPL-2.0 
component  : programming.library
summary    : Script-driven curses widgets
description: |
    Dialog is a script interface for command-line GUI creation.
builddeps  :
    - bash
    - pkgconfig(ncursesw)
setup      : |
    %configure --enable-nls --with-ncursesw
build      : |
    %make
install    : |
    %make_install
