name       : dialog
version    : '1.3_20170131'
release    : 4
source     :
    - https://getsol.us/sources/dialog-1.3-20170131.tgz : 81baec14cb7d76951763576ec276210b3a869e768ad5e2e6ee1cc53420ece8c9
license    : GPL-2.0
component  : programming.library
summary    : Script-driven curses widgets
description: |
    Dialog is a script interface for command-line GUI creation.
builddeps  :
    - pkgconfig(ncursesw)
patterns   :
    - devel : /usr/bin/dialog-config
setup      : |
    %configure --enable-nls \
               --with-ncursesw \
               --disable-static \
               --with-libtool \
               --enable-shared
build      : |
    %make
install    : |
    %make_install
